site_name: AWP Mechanical Handbook

theme:
  name: material
  logo: /assets/awp-logo.png
  favicon: /assets/awp-logo.png
  features:
    - navigation.tracking
    - navigation.tabs
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: custom    
      accent: custom
    - scheme: slate       
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css:
  - styles/extra.css   # load our CSS overrides

nav:
  - Home: index.md
  - Conversions: standards/conversions.md
  - Equations: standards/equations.md
  - Laws: 
    - standards/powerlaws.md
    - standards/fanlaws.md
  - Air Design:
    - standards/pyschometricchart.md
    - standards/pipe_friction_chart.md
    - standards/air_diffusers.md
    - standards/cooling_load.md
    - standards/ductworkabbreviations.md
    - standards/ductwork_rules.md
    - standards/ductsystemresistance.md
    - standards/ductulator.md
    - standards/filter_data.md
    
  - Water Design:
    - standards/pressure.md
  - Extracts from BCA Section J:
    - standards/climate.md



markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
